### ISSUE TITLE
Adapt ALIS to another Visual Studio versions

### ISSUE THREAD

**Issue by RaulLozanoPonce** [pabllopf/Alis#10]
Hi,

It seems that ALIS is only compatible with the 2019 version of Visual Studio. Could it be backward compatible?

**Comment by pabllopf** [comment]
Hi RaulLozanoPonce

In principle, it has not been planned to include this type of compatibility with previous versions of visual studio with the examples that are prepared in version 1.3.6. However, I think it's a very good idea and I'm signing up for the next version to include this type of example.
