### ISSUE TITLE
Alis problems

### ISSUE THREAD

**Issue by RaulLozanoPonce** [pabllopf/Alis#19]
Hi,

I have been used Alis these days, and i found some problems:

- OnCollisionEnter method doesn't work correctly.
- GameObject initial positions are the coordinates (0,0) when I change the initial position with the transform and I move the game object.
- Debug mode doesn't work.
- I need to change the scene.
- Colliders don't rotate with the GameObject transform.
- I need to reference scenes with an index or name.

**Comment by pabllopf** [comment]
Hi RaulLozanoPonce
Of the 6 problems you report, 5 of them are already solved in the latest version of Alis (1.3.6).

On the other hand, I can't understand what you mean by "Debug mode doesn't work." since on my computer I can use that mode without problems.

Thank you and I await your response.

**Comment by RaulLozanoPonce** [comment]
I meant that there was no difference between debug and normal mode, not even the collision boxes.
