### ISSUE TITLE
Alis UI

### ISSUE THREAD

**Issue by RaulLozanoPonce** [pabllopf/Alis#20]
I think that this framework should have UI elements as print text, polygons, or simple sprites. It's uncomfortable having to create different game objects with sprites for each UI element.

**Comment by pabllopf** [comment]
Hi RaulLozanoPonce,

Thanks a lot for the suggestion. Among the planned medium and long-term goals, I planned to include some kind of customizable UI. If it's okay with you, do I close this issue and add it as a HU?

**Comment by RaulLozanoPonce** [comment]
Okay, I'll wait for the next update.
