### ISSUE TITLE
I have a bug on the scene

### ISSUE THREAD

**Issue by suarez0965** [pabllopf/Alis#21]
There is something wrong with my scene background!!

Every time I add an object it starts to duplicate itself. 

There is no problem when I launch the game, but it is discomfort.

![issue allis](https://user-images.githubusercontent.com/82760316/117552761-4d3ce300-b045-11eb-8975-2835428d40f9.PNG)

**Comment by pabllopf** [comment]
Hi suarez0965 

I am analyzing the incident you report, but when I try to reproduce it on my computer I can't. Could you tell me which version of Alis you are working on?
